# Generated by Django 5.2.8 on 2025-11-25 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm_tree_detect_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PalmInfo',
            fields=[
                ('palm_id', models.AutoField(primary_key=True, serialize=False)),
                ('x_min', models.FloatField()),
                ('y_min', models.FloatField()),
                ('x_max', models.FloatField()),
                ('y_max', models.FloatField()),
                ('confidence', models.FloatField()),
                ('date_processed', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='palm_tree_detect_api.palmimage')),
            ],
            options={
                'db_table': 'palm_info',
            },
        ),
    ]
