# Generated by Django 5.2.8 on 2025-11-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm_tree_detect_api', '0002_palminfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Palm Tree Detection System', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'dashboard_design',
            },
        ),
    ]
