# Generated by Django 5.2.8 on 2025-12-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm_tree_detect_api', '0003_dashboarddesign'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100)),
                ('menu_icon', models.CharField(blank=True, max_length=100, null=True)),
                ('menu_link', models.CharField(blank=True, max_length=200, null=True)),
                ('menu_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'menu_design',
            },
        ),
    ]
