# Generated by Django 5.2.8 on 2025-12-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm_tree_detect_api', '0004_menudesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menudesign',
            name='menu_icon',
            field=models.ImageField(blank=True, null=True, upload_to='menu_icons/'),
        ),
    ]
