# Generated by Django 5.2.8 on 2025-12-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm_tree_detect_api', '0005_alter_menudesign_menu_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsInfo',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='aboutus/')),
                ('position', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'aboutus_info',
            },
        ),
    ]
