# Generated by Django 5.2.8 on 2025-12-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm_tree_detect_api', '0006_aboutusinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusinfo',
            name='interested_at',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
